#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

scheduler = Rufus::Scheduler.new
logger = Logger.new('log/rufus.log')

scheduler.every('1m') do
  documents = Document.todo_from_ui.limit(5)

  documents.each do |document|
    begin
      document.inprogress!
      patent_detail_extractor = PatentDetailExtractor.new([document])
      patent_detail_extractor.extract!
      document.completed!
    rescue => exception
      document.update_attributes(status: :failed, exception: exception)
      logger.error(exception)
    end
  end
end

scheduler.join
