#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

scheduler = nil
begin
  scheduler = OCRProcessor.new.schedule_ocr!
  scheduler.join
rescue Rufus::Scheduler::NotRunningError => rufus_exception
  Honeybadger.notify(rufus_exception)
rescue => e
  scheduler.shutdown
  Honeybadger.notify(e, context: {notice: 'Time to shutdown the jobs due to some issues.'})
end
