#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

scheduler = nil
begin
  scheduler = OCRProcessor.new.schedule_ocr!
  scheduler.join
rescue Rufus::Scheduler::NotRunningError => rufus_exception
  Rails.logger.error(rufus_exception.message + "\n" + rufus_exception.backtrace.join("\n"))
rescue => e
  scheduler.shutdown
  Rails.logger.error("Time to shutdown the jobs due to the exception: #{e}")
end
