#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

documents = LitDocument.where('document_status_id = ? AND ocr_text != ? AND ocr_text_s3_path IS NULL', 3, '-- NOT OCR-ED --')
documents.find_each(batch_size: 200) do | document|
  begin
    ocr_text_s3_key = "lit-documents/#{SecureRandom.hex(3)}/#{document.id}.txt"
    S3Uploader.new(document.ocr_text).save_to_s3(ocr_text_s3_key)

    attrs = {ocr_text_s3_path: ocr_text_s3_key, ocr_exception: nil, ocred_at: Time.now, needs_ocr: false}
    document.update_attributes(attrs)
    puts "Saved ocr text of lit document #{document.id} to S3: #{ocr_text_s3_key}"
  rescue => e
    Honeybadger.notify(exception, context: {document_id: document.id, document_type: LitDocument})
  end
end
